import{a as m,S as w,i as n}from"./assets/vendor-ee72e1a4.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))u(s);new MutationObserver(s=>{for(const r of s)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&u(l)}).observe(document,{childList:!0,subtree:!0});function o(s){const r={};return s.integrity&&(r.integrity=s.integrity),s.referrerPolicy&&(r.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?r.credentials="include":s.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function u(s){if(s.ep)return;s.ep=!0;const r=o(s);fetch(s.href,r)}})();m.defaults.baseURL="https://pixabay.com/api";const d=15,b="43654443-0aa2ac279d0400a8e119738dd",y=async(t,e)=>(await m.get("https://pixabay.com/api",{params:{key:b,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:d,page:e}})).data,S=document.querySelector(".gallery");let v=new w(".gallery a",{captionsData:"alt",captionDelay:250});const g=t=>{const e=t.hits.map(o=>`<li class="gallery-item">
            <a class="gallery-link" href=${o.largeImageURL}>
                <img
                    src=${o.webformatURL}
                    alt=${o.tags}
                />
            </a>
                 <div>
                <p><span>Likes</span> ${o.likes}</p>
                <p><span>Views</span> ${o.views}</p>
                <p><span>Comments</span> ${o.comments}</p>
                <p><span>Downloads</span> ${o.downloads}</p>
            </div>
                </li>`).join("");S.insertAdjacentHTML("beforeend",e),v.refresh()},$=document.querySelector("form"),q=document.querySelector(".gallery"),f=document.querySelector(".loader"),p=document.querySelector(".js-load-more");let a=1,i;n.settings({progressBar:!1,timeout:4e3,resetOnHover:!0,icon:"material-icons",transitionIn:"flipInX",transitionOut:"flipOutX",position:"topRight"});const h=()=>f.classList.remove("is-hidden"),L=()=>f.classList.add("is-hidden"),O=()=>p.classList.remove("is-hidden"),c=()=>p.classList.add("is-hidden"),P=async t=>{if(t.preventDefault(),i=t.target.elements.search.value.trim(),!!i){h(),c(),q.innerHTML="";try{a=1;const e=await y(i,a);e.hits.length===0?(c(),n.show({message:"Sorry, there are no images matching your search query. Please try again!"})):(g(e),e.totalHits>d&&O())}catch(e){n.error({message:`Error: ${e.message}`})}finally{t.target.reset(),L()}}},I=async()=>{a+=1;try{const t=await y(i,a),e=Math.ceil(t.totalHits/d);h(),g(t),B(),a>=e&&(c(),n.error({position:"topRight",message:"We're sorry, there are no more posts to load"}))}catch(t){n.error({message:`Error: ${t.message}`})}finally{L()}};$.addEventListener("submit",P);p.addEventListener("click",I);const B=()=>{const t=document.querySelector(".gallery-item");if(t){const e=t.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}};
//# sourceMappingURL=commonHelpers.js.map
