import{a as m,S as b,i as n}from"./assets/vendor-ee72e1a4.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))u(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&u(l)}).observe(document,{childList:!0,subtree:!0});function o(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function u(r){if(r.ep)return;r.ep=!0;const s=o(r);fetch(r.href,s)}})();m.defaults.baseURL="https://pixabay.com/api/";const d=15,w="44242951-779ddab31bb84492c2ee50b34",g=async(t,e)=>(await m.get("",{params:{key:w,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:d,page:e}})).data,S=document.querySelector(".gallery");let v=new b(".gallery a",{captionsData:"alt",captionDelay:250});const y=t=>{const e=t.hits.map(o=>`<li class="gallery-item">
            <a class="gallery-link" href=${o.largeImageURL}>
                <img
                    src=${o.webformatURL}
                    alt=${o.tags}
                />
            </a>
                 <div>
                <p><span>Likes</span> ${o.likes}</p>
                <p><span>Views</span> ${o.views}</p>
                <p><span>Comments</span> ${o.comments}</p>
                <p><span>Downloads</span> ${o.downloads}</p>
            </div>
                </li>`).join("");S.insertAdjacentHTML("beforeend",e),v.refresh()},$=document.querySelector("form"),q=document.querySelector(".gallery"),f=document.querySelector(".loader"),p=document.querySelector(".js-load-more");let a=1,i;n.settings({progressBar:!1,timeout:4e3,resetOnHover:!0,icon:"material-icons",transitionIn:"flipInX",transitionOut:"flipOutX",position:"topRight"});const h=()=>f.classList.remove("is-hidden"),L=()=>f.classList.add("is-hidden"),O=()=>p.classList.remove("is-hidden"),c=()=>p.classList.add("is-hidden"),P=async t=>{if(t.preventDefault(),i=t.target.elements.search.value.trim(),!!i){h(),c(),q.innerHTML="";try{a=1;const e=await g(i,a);e.hits.length===0?(c(),n.show({message:"Sorry, there are no images matching your search query. Please try again!"})):(y(e),e.totalHits>d&&O())}catch(e){n.error({message:`Error: ${e.message}`})}finally{t.target.reset(),L()}}},I=async()=>{a+=1;try{const t=await g(i,a),e=Math.ceil(t.totalHits/d);h(),y(t),B(),a>=e&&(c(),n.error({position:"topRight",message:"We're sorry, there are no more posts to load"}))}catch(t){n.error({message:`Error: ${t.message}`})}finally{L()}};$.addEventListener("submit",P);p.addEventListener("click",I);const B=()=>{const t=document.querySelector(".gallery-item");if(t){const e=t.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}};
//# sourceMappingURL=commonHelpers.js.map
